import turtle as tp
tp.screensize(800,800,"black")
tp.shape("turtle")
tp.pensize(2)
tp.speed(5)
tp.hideturtle()
def draw_circle(x,y,r,color):
    tp.pencolor(color)
    tp.penup()
    tp.goto(x,y)
    tp.pendown()
    tp.fillcolor(color)
    tp.begin_fill()
    tp.circle(r)
    tp.end_fill()
def draw_star(x,y,size,color):
    tp.pencolor(color)
    tp.fillcolor(color)
    tp.penup()
    tp.goto(x,y)
    tp.pendown()
    tp.begin_fill()
    for i in range(5):
        tp.fd(size)
        tp.rt(144)
    tp.end_fill()
draw_circle(0,-70,160,"red")
draw_circle(0,-30,120,"white")
draw_circle(0,10,80,"red")
draw_circle(0,35,55,"blue")
draw_star(-50,105,100,"white")
w=tp.Screen()
w.exitonclick()
