
print("    *")
print("   ***")
print("  *****")
print(" *******")
print("*********")
print("")
print("      _   _")
print("     ((\o/))")
print(".-----//^\\\\-----.")
print("|    /`| |`\    |")
print("|      | |      |")
print("|      | |      |")
print("|      | |      |")
print("|      | |      |")
print("`______---______'")
print("       ---")
